language: cpp
os: linux
dist: focal
compiler:
  - clang

addons:
  apt:
    packages:
      - clang-10
      - libc++-10-dev
      - libc++abi-10-dev
  
  
before_install:
  - sudo apt update 
  - sudo apt -y install libboost-all-dev
  - sudo apt -y install ninja-build
  - eval "CC=clang-10 && CXX=clang-10"

script:
  - mkdir build
  - cd build
  - cmake -G Ninja ..
  - cmake --build .
  - ./CheckCompileTimes
