language: cpp
os: linux
dist: focal
compiler:
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libboost-all-dev
  - sudo apt-get -y install ninja-build

script:
  - mkdir build
  - cd build
  - cmake -G Ninja ..
  - cmake --build .

